In [4]:
import pyarrow.parquet as pq
from IPython.display import display

path = "../data/interim/traffic_weather_metr_la.parquet"

pf = pq.ParquetFile(path)
batch = next(pf.iter_batches(batch_size=20))
df_sample = batch.to_pandas()

display(df_sample)
print(df_sample.shape)
print(df_sample.dtypes)

,dataset,timestamp,sensor_id,speed,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weather_code,...,bridge,tunnel,junction,access,width,length,distance_to_road_m,road_match_status,weather_available,street_available
0,METR-LA,2012-03-01,773869,64.375000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,701.472486,2.156327,matched,1,1
1,METR-LA,2012-03-01,717571,69.250000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,595.918027,5.520935,matched,1,1
2,METR-LA,2012-03-01,767621,64.375000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,923.776509,1.608606,matched,1,1
3,METR-LA,2012-03-01,769372,65.500000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,640.434833,3.892720,matched,1,1
4,METR-LA,2012-03-01,767470,60.500000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,325.970782,1.472691,matched,1,1
5,METR-LA,2012-03-01,763995,69.500000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,341.134739,2.040458,matched,1,1
6,METR-LA,2012-03-01,717804,61.250000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,367.812320,10.727179,matched,1,1
7,METR-LA,2012-03-01,717510,61.625000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,610.429380,2.077124,matched,1,1
8,METR-LA,2012-03-01,773953,55.750000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,1044.834225,2.874372,matched,1,1
9,METR-LA,2012-03-01,772596,65.250000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,828.130480,2.196241,matched,1,1
10,METR-LA,2012-03-01,765099,66.375000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,165.982204,0.865050,matched,1,1
11,METR-LA,2012-03-01,773974,52.125000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,389.618737,3.296354,matched,1,1
12,METR-LA,2012-03-01,737529,59.625000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,399.121675,2.411591,matched,1,1
13,METR-LA,2012-03-01,716554,63.500000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,252.081478,1.222650,matched,1,1
14,METR-LA,2012-03-01,765265,53.125000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,1096.366914,1.148159,matched,1,1
15,METR-LA,2012-03-01,717572,67.125000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,850.252850,0.137229,matched,1,1
16,METR-LA,2012-03-01,717816,62.750000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,102.026702,3.850555,matched,1,1
17,METR-LA,2012-03-01,717504,63.750000,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,975.837617,3.072528,matched,1,1
18,METR-LA,2012-03-01,716955,51.571429,8.0,93,0.0,0.0,0.0,0,...,yes,<NA>,<NA>,<NA>,NaN,1003.099152,0.062680,matched,1,1
19,METR-LA,2012-03-01,718089,61.375000,8.0,93,0.0,0.0,0.0,0,...,<NA>,<NA>,<NA>,<NA>,NaN,1195.224484,3.001024,matched,1,1

(20, 36)
dataset                            str
timestamp               datetime64[us]
sensor_id                       string
speed                          float64
temperature_2m                 float64
relative_humidity_2m             int64
precipitation                  float64
rain                           float64
snowfall                       float64
weather_code                     int64
visibility                     float64
wind_speed_10m                 float64
cloud_cover                      int64
surface_pressure               float64
is_fog                           int64
is_rain                          int64
is_snow                          int64
is_thunderstorm                  int64
latitude                       float64
longitude                      float64
osmid                           string
name                            string
highway                         string
lanes                           string
maxspeed                        string
oneway                          string
bridge                          string
tunnel                          string
junction                        string
access                          string
width                          float64
length                         float64
distance_to_road_m             float64
road_match_status               string
weather_available                 int8
street_available                  int8
dtype: object

In [1]:
from pathlib import Path
import pyarrow.parquet as pq

path = Path("../data/interim/traffic_weather_pems_bay.parquet")

print("Exists:", path.exists())
print("File size (GB):", round(path.stat().st_size / 1e9, 2))

pf = pq.ParquetFile(path)

print("Rows:", pf.metadata.num_rows)
print("Row groups:", pf.metadata.num_row_groups)
print("Columns:", pf.schema.names)
print(pf.schema)

Exists: True
File size (GB): 0.19
Rows: 16937700
Row groups: 1629
Columns: ['dataset', 'timestamp', 'sensor_id', 'speed', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'snowfall', 'weather_code', 'visibility', 'wind_speed_10m', 'cloud_cover', 'surface_pressure', 'is_fog', 'is_rain', 'is_snow', 'is_thunderstorm', 'latitude', 'longitude', 'osmid', 'name', 'highway', 'lanes', 'maxspeed', 'oneway', 'bridge', 'tunnel', 'junction', 'access', 'width', 'length', 'distance_to_road_m', 'road_match_status', 'weather_available', 'street_available']
<pyarrow._parquet.ParquetSchema object at 0x72f8a91b9b80>
required group field_id=-1 schema {
  optional binary field_id=-1 dataset (String);
  optional int64 field_id=-1 timestamp (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional binary field_id=-1 sensor_id (String);
  optional double field_id=-1 speed;
  optional double field_id=-1 temperature_2m;
  optional double field_id=-1 relative_humidity_2m;
  optional double field_id=-1 precipitation;
  optional double field_id=-1 rain;
  optional double field_id=-1 snowfall;
  optional double field_id=-1 weather_code;
  optional double field_id=-1 visibility;
  optional double field_id=-1 wind_speed_10m;
  optional double field_id=-1 cloud_cover;
  optional double field_id=-1 surface_pressure;
  optional double field_id=-1 is_fog;
  optional double field_id=-1 is_rain;
  optional double field_id=-1 is_snow;
  optional double field_id=-1 is_thunderstorm;
  optional double field_id=-1 latitude;
  optional double field_id=-1 longitude;
  optional binary field_id=-1 osmid (String);
  optional binary field_id=-1 name (String);
  optional binary field_id=-1 highway (String);
  optional binary field_id=-1 lanes (String);
  optional binary field_id=-1 maxspeed (String);
  optional binary field_id=-1 oneway (String);
  optional binary field_id=-1 bridge (String);
  optional binary field_id=-1 tunnel (String);
  optional binary field_id=-1 junction (String);
  optional binary field_id=-1 access (String);
  optional double field_id=-1 width;
  optional double field_id=-1 length;
  optional double field_id=-1 distance_to_road_m;
  optional binary field_id=-1 road_match_status (String);
  optional int32 field_id=-1 weather_available (Int(bitWidth=8, isSigned=true));
  optional int32 field_id=-1 street_available (Int(bitWidth=8, isSigned=true));
}

In [2]:
import pandas as pd

pf = pq.ParquetFile(path)
batch = next(pf.iter_batches(batch_size=20))
df_sample = batch.to_pandas()

display(df_sample)
print(df_sample.dtypes)

,dataset,timestamp,sensor_id,speed,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weather_code,...,bridge,tunnel,junction,access,width,length,distance_to_road_m,road_match_status,weather_available,street_available
0,PEMS-BAY,2017-01-01,400001,71.4,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,233.799076,0.809523,matched,1,1
1,PEMS-BAY,2017-01-01,400400,68.1,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,288.909945,0.431056,matched,1,1
2,PEMS-BAY,2017-01-01,407161,68.8,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,610.877617,5.113583,matched,1,1
3,PEMS-BAY,2017-01-01,400414,67.4,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,835.068423,4.055831,matched,1,1
4,PEMS-BAY,2017-01-01,407157,69.2,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,1189.861390,3.340836,matched,1,1
5,PEMS-BAY,2017-01-01,400418,68.0,7.5,71.0,0.0,0.0,0.0,0.0,...,yes,<NA>,<NA>,<NA>,NaN,1666.745505,13.300074,matched,1,1
6,PEMS-BAY,2017-01-01,407155,69.0,7.5,71.0,0.0,0.0,0.0,0.0,...,yes,<NA>,<NA>,<NA>,NaN,764.932018,4.415238,matched,1,1
7,PEMS-BAY,2017-01-01,400429,68.3,7.5,71.0,0.0,0.0,0.0,0.0,...,yes,<NA>,<NA>,<NA>,NaN,1239.422425,1.932251,matched,1,1
8,PEMS-BAY,2017-01-01,407153,69.3,7.5,71.0,0.0,0.0,0.0,0.0,...,yes,<NA>,<NA>,<NA>,NaN,845.710984,2.389057,matched,1,1
9,PEMS-BAY,2017-01-01,400435,70.1,7.5,71.0,0.0,0.0,0.0,0.0,...,yes,<NA>,<NA>,<NA>,NaN,825.776442,0.598677,matched,1,1
10,PEMS-BAY,2017-01-01,407152,69.7,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,1126.389929,4.153167,matched,1,1
11,PEMS-BAY,2017-01-01,400436,67.9,7.5,71.0,0.0,0.0,0.0,0.0,...,yes,<NA>,<NA>,<NA>,NaN,632.737357,4.177270,matched,1,1
12,PEMS-BAY,2017-01-01,407151,69.5,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,1150.018794,2.223443,matched,1,1
13,PEMS-BAY,2017-01-01,400440,68.7,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,306.658280,0.144651,matched,1,1
14,PEMS-BAY,2017-01-01,407150,69.9,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,1150.018794,1.881339,matched,1,1
15,PEMS-BAY,2017-01-01,405701,70.5,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,583.496637,5.307583,matched,1,1
16,PEMS-BAY,2017-01-01,407165,69.0,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,295.147307,6.448104,matched,1,1
17,PEMS-BAY,2017-01-01,400449,67.5,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,1399.848955,1.022937,matched,1,1
18,PEMS-BAY,2017-01-01,400394,72.1,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,297.435098,5.879472,matched,1,1
19,PEMS-BAY,2017-01-01,400372,69.1,7.5,71.0,0.0,0.0,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,NaN,225.651433,4.493371,matched,1,1

dataset                            str
timestamp               datetime64[us]
sensor_id                       string
speed                          float64
temperature_2m                 float64
relative_humidity_2m           float64
precipitation                  float64
rain                           float64
snowfall                       float64
weather_code                   float64
visibility                     float64
wind_speed_10m                 float64
cloud_cover                    float64
surface_pressure               float64
is_fog                         float64
is_rain                        float64
is_snow                        float64
is_thunderstorm                float64
latitude                       float64
longitude                      float64
osmid                           string
name                            string
highway                         string
lanes                           string
maxspeed                        string
oneway                          string
bridge                          string
tunnel                          string
junction                        string
access                          string
width                          float64
length                         float64
distance_to_road_m             float64
road_match_status               string
weather_available                 int8
street_available                  int8
dtype: object